name: Alt-CI

on:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  integration:
    name: Test crate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
#          - ubuntu-18.04
#          - macos-11.0
#          - macos-10.15
#         - macos-10.13   # only image without Rust 1.48.0
        toolchain:
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          path: .
          submodules: recursive

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Unit Tests
        run: cargo test --lib
