name: Alt-CI

on:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  integration:
    name: Test crate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
#          - ubuntu-18.04
#          - macos-11.0
#          - macos-10.15
#         - macos-10.13   # only image without Rust 1.48.0
        toolchain:
          - stable

    steps:
      - name: Checkout
        run: |
          git clone --recurse-submodules ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} .
          ARCH=$(uname -m)

      - name: Cache Cargo Artifacts
        uses: actions/cache@v2
        env:
          ARCH: ${{ env.ARCH }}
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: |
            ${{ matrix.os }}-${{ env.ARCH }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-${{ env.ARCH }}-cargo-${{ hashFiles('**/Cargo.toml') }}-
            ${{ matrix.os }}-${{ env.ARCH }}-cargo-

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Unit Tests
        run: cargo test --lib
