name: Alt-CI

on:
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  integration:
    name: Test crate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
#          - ubuntu-18.04
#          - macos-11.0
#          - macos-10.15
#         - macos-10.13   # only image without Rust 1.48.0
        toolchain:
          - stable

    steps:
      - name: Checkout
        run: |
          git clone --recurse-submodules https://github.com/franckrasolo/slice.rs .
          git -C tests/resources/test-repo status
          git -C tests/resources/test-repo log c89ad800371ebf5300212ddd0523b14534fc99cc..764ecf6ed4de341203b9c9af94db4ac279c087fe

      - name: List File Tree
        run: |
          set -o xtrace
          echo ">>> pwd: $(pwd)"
          ls -alh ..
          cargo --version
          rustc --version
          echo ">>> CARGO_MANIFEST_DIR=${CARGO_MANIFEST_DIR}"
          ls -alhR

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Unit Tests
        run: cargo test --lib
