name: CI

on:
  push:
    branches:
      - main
      - 'dependabot/cargo/**'
    paths-ignore:
      - '.*ignore'
      - '.editorconfig'
      - '.envrc'
      - '.justfile'
      - '**.md'
      - '**.png'
      - 'flake.*'
      - 'LICENSE'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - macos-15
          - macos-14
        toolchain:
          - stable
    steps:
      - name: Checkout
        id: checkout
        run: |
          git clone --recurse-submodules ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} .
          echo "{hw_isa}={$(uname -m)}" >> $GITHUB_OUTPUT

      - name: Cache Cargo Artifacts
        uses: actions/cache@v4
        env:
          CACHE_KEY_PREFIX: ${{ matrix.os }}-${{ steps.checkout.outputs.hw_isa }}-cargo
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/Cargo.toml') }}-
            ${{ env.CACHE_KEY_PREFIX }}-

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Unit Tests
        run: cargo test --lib
