name: CI

on:
  push:
    branches:
      - main
      - 'dependabot/cargo/**'
    paths-ignore:
      - '.*ignore'
      - '.editorconfig'
      - '**.md'
      - '**.png'
      - 'LICENSE'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11
          - macos-10.15
          - macos-10.13
        toolchain:
          - stable
    steps:
      - name: Clean Up
        if: ${{ matrix.os == 'macos-10.13' }}
        run: |
          cd "${{ github.workspace }}/.." && rm -rf *
          mkdir -pv "${{ github.workspace }}" && cd "${{ github.workspace }}"
      - name: Checkout
        id: checkout
        run: |
          git clone --recurse-submodules ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} .
          echo ::set-output name=hw_isa::$(uname -m)

      - name: Cache Cargo Artifacts
        uses: actions/cache@v2
        env:
          CACHE_KEY_PREFIX: ${{ matrix.os }}-${{ steps.checkout.outputs.hw_isa }}-cargo
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/Cargo.toml') }}-
            ${{ env.CACHE_KEY_PREFIX }}-

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Unit Tests
        run: cargo test --lib
