name: CI

on:
  push:
    paths-ignore:
      - '.*ignore'
      - '**.md'
      - '**.png'
      - '**.txt'
      - '**.yml'
      - 'LICENSE'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1

jobs:
  integration:
    name: Test crate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-11.0
          - macos-10.15
          - macos-10.13   # only image without Rust 1.48.0
        toolchain:
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: clippy

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib
