name: Security Audit
on:
  push:
    paths:
      - '.github/workflows/security-audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 7-17/5 * * *'
  workflow_dispatch:

permissions: read-all

jobs:
  security-audit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/audit@v1
        name: Audit Rust Dependencies
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
