# ShiftLeft Scan is a free open-source security tool for modern DevOps teams
# https://slscan.io/en/latest/integrations/code-scan
name: ShiftLeft Scan

on:
  push:
  workflow_dispatch:

jobs:
  scan-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Scan
        uses: ShiftLeftSecurity/scan-action@master
        env:
          WORKSPACE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_AUTO_BUILD: true
        with:
          output: reports
          type: rust

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports
